services:
  api:
    container_name: grabarr-api
    image: ghcr.io/d3v1l1989/grabarr-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      - DATABASE_URL=sqlite:///./data/grabarr.db
      - PROJECT_NAME=Grabarr
      - VERSION=1.0.0
      - API_V1_STR=/api/v1
    volumes:
      - api_data:/app/data
      - ./.env:/app/.env
    env_file:
      - .env

  frontend:
    container_name: grabarr-frontend
    image: ghcr.io/d3v1l1989/grabarr-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3456:3456"
    environment:
      - REACT_APP_API_URL=http://localhost:8765
    depends_on:
      - api

volumes:
  api_data: