version: '3.8'

services:
  api:
    container_name: grabarr-api
    image: ghcr.io/d3v1l1989/grabarr-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      - DATABASE_URL=sqlite:///./data/grabarr.db
      - API_KEY=${API_KEY}
      - ENVIRONMENT=production
    volumes:
      - api_data:/app/data

  frontend:
    container_name: grabarr-frontend
    image: ghcr.io/d3v1l1989/grabarr-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3456:3456"
    environment:
      - REACT_APP_API_URL=http://localhost:8765
      - REACT_APP_ENVIRONMENT=production
    depends_on:
      - api

volumes:
  api_data: 