name: Development Workspace

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Start development environment
        run: |
          docker-compose up -d api frontend
          
      - name: Wait for services to be ready
        run: |
          sleep 10
          
      - name: Check API health
        run: |
          curl -f http://localhost:8765/health 